name: Test

on: [workflow_dispatch]

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install beautifulsoup4
      - run: python ./get_twig.py
